"""Initial migration

Revision ID: 14ff571a5267
Revises: 
Create Date: 2026-06-15 17:01:15.224709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ff571a5267'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dificulty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Dificulty_id'), 'Dificulty', ['id'], unique=False)
    op.create_table('Permision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permision_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permision_name')
    )
    op.create_index(op.f('ix_Permision_id'), 'Permision', ['id'], unique=False)
    op.create_table('Role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Role_id'), 'Role', ['id'], unique=False)
    op.create_index(op.f('ix_Role_name'), 'Role', ['name'], unique=True)
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('Permision_Role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permision_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permision_id'], ['Permision.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Permision_Role_id'), 'Permision_Role', ['id'], unique=False)
    op.create_table('Recipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dificuly_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dificuly_id'], ['Dificulty.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Recipe_id'), 'Recipe', ['id'], unique=False)
    op.create_table('User_Role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_Role_id'), 'User_Role', ['id'], unique=False)
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Comment_id'), 'Comment', ['id'], unique=False)
    op.create_table('Ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ingredients_id'), 'Ingredients', ['id'], unique=False)
    op.create_table('Recipe_Image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Recipe_Image_id'), 'Recipe_Image', ['id'], unique=False)
    op.create_table('Recipe_Info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cook_time', sa.Integer(), nullable=True),
    sa.Column('preparation_time', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id')
    )
    op.create_index(op.f('ix_Recipe_Info_id'), 'Recipe_Info', ['id'], unique=False)
    op.create_table('Recipe_Rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('value BETWEEN 1 AND 5', name='check_rating_value'),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Recipe_Rating_id'), 'Recipe_Rating', ['id'], unique=False)
    op.create_table('Step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Step_id'), 'Step', ['id'], unique=False)
    op.create_table('Ingredient_Image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['Ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ingredient_Image_id'), 'Ingredient_Image', ['id'], unique=False)
    op.create_table('Step_Image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['Step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Step_Image_id'), 'Step_Image', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Step_Image_id'), table_name='Step_Image')
    op.drop_table('Step_Image')
    op.drop_index(op.f('ix_Ingredient_Image_id'), table_name='Ingredient_Image')
    op.drop_table('Ingredient_Image')
    op.drop_index(op.f('ix_Step_id'), table_name='Step')
    op.drop_table('Step')
    op.drop_index(op.f('ix_Recipe_Rating_id'), table_name='Recipe_Rating')
    op.drop_table('Recipe_Rating')
    op.drop_index(op.f('ix_Recipe_Info_id'), table_name='Recipe_Info')
    op.drop_table('Recipe_Info')
    op.drop_index(op.f('ix_Recipe_Image_id'), table_name='Recipe_Image')
    op.drop_table('Recipe_Image')
    op.drop_index(op.f('ix_Ingredients_id'), table_name='Ingredients')
    op.drop_table('Ingredients')
    op.drop_index(op.f('ix_Comment_id'), table_name='Comment')
    op.drop_table('Comment')
    op.drop_index(op.f('ix_User_Role_id'), table_name='User_Role')
    op.drop_table('User_Role')
    op.drop_index(op.f('ix_Recipe_id'), table_name='Recipe')
    op.drop_table('Recipe')
    op.drop_index(op.f('ix_Permision_Role_id'), table_name='Permision_Role')
    op.drop_table('Permision_Role')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Role_name'), table_name='Role')
    op.drop_index(op.f('ix_Role_id'), table_name='Role')
    op.drop_table('Role')
    op.drop_index(op.f('ix_Permision_id'), table_name='Permision')
    op.drop_table('Permision')
    op.drop_index(op.f('ix_Dificulty_id'), table_name='Dificulty')
    op.drop_table('Dificulty')
    # ### end Alembic commands ###
